// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXXnI1iU2C5Rf4A_sBvJMvFsE0g7YaCxU',
    appId: '1:1025156994550:web:6234da222038bbe051e3d7',
    messagingSenderId: '1025156994550',
    projectId: 'auth-firebase-39a0f',
    authDomain: 'auth-firebase-39a0f.firebaseapp.com',
    storageBucket: 'auth-firebase-39a0f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJYbId489UK4aQlL-YjIUH4rRNdXiSGvg',
    appId: '1:1025156994550:android:5b1ca8e4a352fbfa51e3d7',
    messagingSenderId: '1025156994550',
    projectId: 'auth-firebase-39a0f',
    storageBucket: 'auth-firebase-39a0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM7IG2B41dN06OHlQOii51Ccvm2WNbdzE',
    appId: '1:1025156994550:ios:885cc6d854cb894051e3d7',
    messagingSenderId: '1025156994550',
    projectId: 'auth-firebase-39a0f',
    storageBucket: 'auth-firebase-39a0f.firebasestorage.app',
    iosBundleId: 'com.example.authfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM7IG2B41dN06OHlQOii51Ccvm2WNbdzE',
    appId: '1:1025156994550:ios:885cc6d854cb894051e3d7',
    messagingSenderId: '1025156994550',
    projectId: 'auth-firebase-39a0f',
    storageBucket: 'auth-firebase-39a0f.firebasestorage.app',
    iosBundleId: 'com.example.authfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXXnI1iU2C5Rf4A_sBvJMvFsE0g7YaCxU',
    appId: '1:1025156994550:web:9cbc3a1facd38ce751e3d7',
    messagingSenderId: '1025156994550',
    projectId: 'auth-firebase-39a0f',
    authDomain: 'auth-firebase-39a0f.firebaseapp.com',
    storageBucket: 'auth-firebase-39a0f.firebasestorage.app',
  );
}
